#!/bin/bash

git reset --hard;
git clean -df;

git checkout master;
rm pt_BR.csv;
wget http://107.170.242.99/var/Head/source_pt_BR.csv -O pt_BR.csv
git add pt_BR.csv;
git commit -m "Updating the translation";

git checkout -b 2.2.2; git checkout 2.2.2;
rm pt_BR.csv;
wget http://107.170.242.99/var/2.2.2/source_pt_BR.csv -O pt_BR.csv
git add . --all;
git commit -m "Updating the translation";

git checkout -b 2.2.1; git checkout 2.2.1;
rm pt_BR.csv;
wget http://107.170.242.99/var/2.2.1/source_pt_BR.csv -O pt_BR.csv
git add . --all;
git commit -m "Updating the translation";

git checkout -b 2.2.0; git checkout 2.2.0;
rm pt_BR.csv;
wget http://107.170.242.99/var/2.2.0/source_pt_BR.csv -O pt_BR.csv
git add . --all;
git commit -m "Updating the translation";

git checkout -b 2.1.8; git checkout 2.1.8;
rm pt_BR.csv;
wget http://107.170.242.99/var/2.1.8/source_pt_BR.csv -O pt_BR.csv
git add . --all;
git commit -m "Updating the translation";

git checkout -b 2.1.5; git checkout 2.1.5;
rm pt_BR.csv;
wget http://107.170.242.99/var/2.1.5/source_pt_BR.csv -O pt_BR.csv
git add . --all;
git commit -m "Updating the translation";

git checkout -b 2.1.0; git checkout 2.1.0;
rm pt_BR.csv;
wget http://107.170.242.99/var/2.1.0/source_pt_BR.csv -O pt_BR.csv
git add . --all;
git commit -m "Updating the translation";

git checkout -b 2.0.7; git checkout 2.0.7;
rm pt_BR.csv;
wget http://107.170.242.99/var/2.0.7/source_pt_BR.csv -O pt_BR.csv
git add . --all;
git commit -m "Updating the translation";

git checkout -b 2.0.2; git checkout 2.0.2;
rm pt_BR.csv;
wget http://107.170.242.99/var/2.0.2/source_pt_BR.csv -O pt_BR.csv
git add . --all;
git commit -m "Updating the translation";

git checkout master;
git push --all;
